services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: always
    networks:
      frontend:
      backend:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/mnt/user/appdata/traefik/traefik.yml:/etc/traefik/traefik.yml"
      - "/mnt/user/appdata/traefik/dynamic:/etc/traefik/dynamic"
      - "/mnt/user/appdata/traefik/certs:/etc/traefik/certs"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  frontend:
    external: true
  backend:
    external: true
